server:
  port: 8090
spring:
  datasource:
    url: jdbc:mariadb://193.122.127.164:3306/spring_batch?useSSL=false&autoReconnect=true&useUnicode=true
    username: batchtest
    password: testbatch
    driver-class-name: org.mariadb.jdbc.Driver

  # 스케쥴 시간 설정 cron 사용
  # cron "초 분 시 일 월 주"
  task:
    scheduling:
      cron:
        gender: "0 * * * * *"
        age: "20 * * * * *"

  batch:
    job:
      enabled: false
      names: makeGenderBatchJob, makeAgeBatchJob
    jdbc:
      initialize-schema: always

logging:
  config: classpath:logback-spring.xml
  level:
    sql: debug

mybatis:
  mapper-locations: classpath:sql/*.xml
  type-aliases-package: com.example.statisticsbatch.persistence.vo, com.example.statisticsbatch.persistence.vo.batch
