spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statisticstest?useSSL=false&autoReconnect=true&useUnicode=true
    username: root
    password: bong
    driver-class-name: com.mysql.cj.jdbc.Driver

# ??? ?? ?? cron ??
# cron "? ? ? ? ? ?"
  task:
    scheduling:
      cron:
        task1: "0 0 8 * * * "
#        task2: "0 0/1 * * * * " << Scheduler? 2? ??? ??

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:sql/*.xml
  type-aliases-package: com.example.statisticsbatch.persistence.vo