spring:
  datasource:
    url: url
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# 스케쥴 시간 설정 cron 사용
# cron "초 분 시 일 월 주"
  task:
    scheduling:
      cron:
        task1: "0 0 8 * * *"
#        task2: "0 0/1 * * *"

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:sql/*.xml
  type-aliases-package: com.example.statisticsbatch.persistence.vo